### ISSUE TITLE
manifest.json not found

### ISSUE THREAD

**Issue by rico64d** [onetimesecret/onetimesecret#1120]
Hi, when starting a container using Docker Compose, I'm having trouble communicating with the backend. Is there any additional flag or option I can use? `onetime-app | E(1739986621): Vite /app/public/web/dist/.vite/manifest.json not found. Run pnpm run build`

```
services:
  app:
    build:
     context: .
     dockerfile: Dockerfile
    container_name: onetime-app
    depends_on:
      - redis
    env_file:
      - .env
    entrypoint: ["./bin/entrypoint.sh"]

    # Makes it possible to interact with the container inside a shell.
    stdin_open: true
    tty: true

    # The bin/entrypoint.sh script already launches the webapp by
    # default but the command can be customized by including one
    # here. When supplied as a list, each string will be properly
    # escaped to avoid shell injection vulnerabilities.
    #
    #   e.g.
    #
    # command: ["bundle", "exec", "thin", "-R", "config.ru", "start"]

    logging:
      driver: "json-file"
      options:
        max-size: "60m"
        max-file: "3"
    ports:
      - 3000:3000

    # Mounts the current working directory (.) into /app inside
    # the container, which is where the webapp lives. This is a
    # convenient way to develop in place without having to rebuild
    # the image each time you make a change.
    volumes:
      - .:/app

  redis:
    image: redis:bookworm@sha256:e422889e156ebea83856b6ff973bfe0c86bce867d80def228044eeecf925592b
    container_name: onetime-redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
      - ./etc/redis.conf:/usr/local/etc/redis/redis.conf

volumes:
  redis-data:
```

```

onetime-app    | ++ date -u
onetime-app    | + datestamp='Wed Feb 19 17:36:35 UTC 2025'
onetime-app    | ++ readlink -f ./bin/entrypoint.sh
onetime-app    | + location=/app/bin/entrypoint.sh
onetime-app    | ++ basename /app/bin/entrypoint.sh
onetime-app    | + basename=entrypoint.sh
onetime-app    | + echo '[Wed Feb 19 17:36:35 UTC 2025] INFO: Running entrypoint.sh...'
onetime-app    | [Wed Feb 19 17:36:35 UTC 2025] INFO: Running entrypoint.sh...
onetime-app    | + unset datestamp location basename
onetime-app    | + [[ true == \t\r\u\e ]]
onetime-app    | + echo 'Running bundle install...'
onetime-app    | Running bundle install...
onetime-app    | + bundle install
onetime-app    | Bundler 2.6.4 is running, but your lockfile was generated with 2.6.3. Installing Bundler 2.6.3 and restarting using that version.
onetime-app    | Fetching gem metadata from https://rubygems.org/.
onetime-app    | Fetching bundler 2.6.3
onetime-app    | Installing bundler 2.6.3
onetime-app    | Bundle complete! 53 Gemfile dependencies, 55 gems now installed.
onetime-app    | Gems in the groups 'development' and 'test' were not installed.
onetime-app    | Use `bundle info [gemname]` to see where a bundled gem is installed.
onetime-app    | + '[' -d /mnt/public ']'
onetime-app    | + '[' -z bundle exec thin -R config.ru start ']'
onetime-app    | ./bin/entrypoint.sh: line 63: [: too many arguments
onetime-app    | + exec bundle exec bundle exec thin -R config.ru start
onetime-app    | D(1739986613): Looking for /etc/onetime/config.yaml
onetime-app    | D(1739986613): Looking for /app/etc/config.yaml
onetime-app    | D(1739986613): Setting TrueMail config from /app/etc/config.yaml
onetime-app    | D(1739986613): Setting Truemail config key default_validation_type to regex
onetime-app    | D(1739986613): Setting Truemail config key verifier_email to CHANGEME@example.com
onetime-app    | D(1739986613): Setting Truemail config key allowed_domains_only to false
onetime-app    | D(1739986613): Setting Truemail config key dns to ["1.1.1.1", "8.8.4.4", "208.67.220.220"]
onetime-app    | D(1739986613): Setting Truemail config key smtp_fail_fast to false
onetime-app    | D(1739986613): Setting Truemail config key smtp_safe_check to true
onetime-app    | D(1739986613): Setting Truemail config key not_rfc_mx_lookup_flow to false
onetime-app    | D(1739986613): Setting Truemail config key logger to {tracking_event: :error, stdout: true}
onetime-app    | Warning: Commit hash file not found. Using default value 'pristine'.
onetime-app    | D(1739986613): Loading locale en: true
onetime-app    | D(1739986613): Loading locale ar: true
onetime-app    | D(1739986613): Loading locale bg: true
onetime-app    | D(1739986613): Loading locale ca_ES: true
onetime-app    | D(1739986613): Loading locale cn: true
onetime-app    | D(1739986613): Loading locale cs: true
onetime-app    | D(1739986613): Loading locale da_DK: true
onetime-app    | D(1739986613): Loading locale de: true
onetime-app    | D(1739986613): Loading locale el_GR: true
onetime-app    | D(1739986613): Loading locale en: true
onetime-app    | D(1739986613): Loading locale es: true
onetime-app    | D(1739986613): Loading locale fr: true
onetime-app    | D(1739986613): Loading locale fr_FR: true
onetime-app    | D(1739986613): Loading locale he: true
onetime-app    | D(1739986613): Loading locale hu: true
onetime-app    | D(1739986613): Loading locale it_IT: true
onetime-app    | D(1739986613): Loading locale nl: true
onetime-app    | D(1739986613): Loading locale pl: true
onetime-app    | D(1739986613): Loading locale pt_BR: true
onetime-app    | D(1739986613): Loading locale pt_PT: true
onetime-app    | D(1739986613): Loading locale ru: true
onetime-app    | D(1739986613): Loading locale sl_SI: true
onetime-app    | D(1739986613): Loading locale sv_SE: true
onetime-app    | D(1739986613): Loading locale tr: true
onetime-app    | D(1739986613): Loading locale uk: true
onetime-app    | D(1739986613): Loading locale vi: true
onetime-app    | D(1739986613): [connect_databases] dbs: {session: 1, splittest: 1, custom_domain: 6, customer: 6, subdomain: 6, metadata: 7, email_receipt: 8, secret: 8, rate_limit: 2, feedback: 11, exception_info: 12}
onetime-app    | D(1739986613): Connected metadata to DB 7 (PONG)
onetime-app    | D(1739986613): Connected secret to DB 8 (PONG)
onetime-app    | D(1739986613): Connected session to DB 1 (PONG)
onetime-app    | D(1739986613): Connected customer to DB 6 (PONG)
onetime-app    | D(1739986613): Connected split_test to DB 0 (PONG)
onetime-app    | D(1739986613): Connected email_receipt to DB 8 (PONG)
onetime-app    | D(1739986613): Connected custom_domain to DB 6 (PONG)
onetime-app    | D(1739986613): Connected feedback to DB 11 (PONG)
onetime-app    | D(1739986613): Connected exception_info to DB 12 (PONG)
onetime-app    | D(1739986613): Connected rate_limit to DB 2 (PONG)
onetime-app    | I(1739986613): ---  ONETIME app v0.19.1 (pristine)  ---------
onetime-app    | I(1739986613): system: ruby-unix-linux-x86_64 (ruby 3.4.2)
onetime-app    | I(1739986613): config: /app/etc/config.yaml
onetime-app    | I(1739986613): redis: 7.2.5 (redis://redis:6379/0)
onetime-app    | I(1739986613): familia: v1.1.0-rc1
onetime-app    | I(1739986613): colonels: CHANGEME@EXAMPLE.com
onetime-app    | I(1739986613): auth: enabled=true, signup=true, signin=true, autoverify=false
onetime-app    | I(1739986613): domains: enabled=false, default=, cluster={type: nil, api_key: nil, cluster_ip: "<CLUSTER_IP>", cluster_host: "<CLUSTER_HOST>", cluster_name: "<CLUSTER_NAME>", vhost_target: "<VHOST_TARGET>"}
onetime-app    | I(1739986613): regions: enabled=false, current_jurisdiction=EU
onetime-app    | I(1739986613): development: enabled=false, debug=true, frontend_host=http://localhost:5173
onetime-app    | I(1739986613): mail: smtp=smtp.provider.com:587, from=CHANGEME@example.com, mode=smtp, tls=, auth=login
onetime-app    | I(1739986613): experimental: freeze_app=false, csp={enabled: false}
onetime-app    | I(1739986613): locales: en, ar, bg, ca_ES, cn, cs, da_DK, de, el_GR, es, fr, fr_FR, he, hu, it_IT, nl, pl, pt_BR, pt_PT, ru, sl_SI, sv_SE, tr, uk, vi
onetime-app    | I(1739986613): secret options: {default_ttl: 604800.0, ttl_options: [300, 1800, 3600, 14400, 43200, 86400, 259200, 604800, 1209600, 2592000]}
onetime-app    | I(1739986613): rate limits: create_secret=1000, create_account=10, update_account=10, email_recipient=50, send_feedback=10, authenticate_session=5, get_page=1000, dashboard=1000, failed_passphrase=5, show_metadata=1000, show_secret=1000, burn_secret=1000, destroy_account=2, forgot_password_request=2, forgot_password_reset=3, generate_apitoken=10, add_domain=30, remove_domain=30, list_domains=100, get_domain=100, verify_domain=25, report_exception=50, attempt_secret_access=10
onetime-app    | I(1739986613): [config.ru] Using Rack::Lint
onetime-app    | I(1739986613): [config.ru] Using Rack::CommonLogger
onetime-app    | I(1739986613): [config.ru] Using Rack::ClearSessionMessages
onetime-app    | I(1739986613): [config.ru] Using Rack::HandleInvalidUTF8
onetime-app    | I(1739986613): [config.ru] Using Rack::HandleInvalidPercentEncoding
onetime-app    | I(1739986613): [config.ru] Using Rack::ContentLength
onetime-app    | I(1739986613): [config.ru] Using Rack::DetectHost
onetime-app    | I(1739986613): [config.ru] Using Onetime::DomainStrategy
onetime-app    | E(1739986613): [DomainStrategy]: Initializing from config1:  
onetime-app    | E(1739986613): [DomainStrategy]: Initializing from config2: false 
onetime-app    | I(1739986613): [DomainStrategy]: canonical_domain=localhost:3000 enabled=false
onetime-app    | 2025-02-19 17:36:53 +0000 Thin web server (v1.8.2 codename Ruby Razor)
onetime-app    | 2025-02-19 17:36:53 +0000 Maximum connections set to 1024
onetime-app    | 2025-02-19 17:36:53 +0000 Listening on 0.0.0.0:3000, CTRL+C to stop
onetime-app    | D(1739986621): [DomainStrategy]: host="localhost:3000" strategy=canonical
onetime-app    | D(1739986621): [index] authenticated? false
onetime-app    | D(1739986621): [OT] llqca2zojhcfqsc5yxx3o86gasqhsm5 get_page 11/1000
onetime-app    | D(1739986621): ["RateLimit.incr!", :get_page, "llqca2zojhcfqsc5yxx3o86gasqhsm5", 11, 1000]
onetime-app    | E(1739986621): Vite /app/public/web/dist/.vite/manifest.json not found. Run `pnpm run build`
onetime-app    | 172.18.0.1 - - [19/Feb/2025:17:37:01 +0000] "GET / HTTP/1.1" 200 10635 0.0747
onetime-app    | D(1739986621): [DomainStrategy]: host="localhost:3000" strategy=canonical
onetime-app    | D(1739986621): [Session.external_identifier] sess identifier input: ["172.18.0.1", "anon"] (result: llqca2zojhcfqsc5yxx3o86gasqhsm5)
onetime-app    | E(1739986621): Vite /app/public/web/dist/.vite/manifest.json not found. Run `pnpm run build`
onetime-app    | 172.18.0.1 - - [19/Feb/2025:17:37:01 +0000] "GET /site.webmanifest?v=3 HTTP/1.1" 404 10635 0.0547

```
