### ISSUE TITLE
UI doesnt work since v0.21.0-rc1 docker

### ISSUE THREAD

**Issue by toprogramm** [onetimesecret/onetimesecret#1259]
# UI doesn't work on docker builds since v0.21.0-rc1, but v0.20.5 works correct.
OS - Ubuntu 24.04.2LTS
UI doesnt work(404 error to download files from /dist/assets/), but theese files exist in the conatainer.  lt doesnt work in *docker-compose mode* and doesnt work in *usual docker mode*. I tried to build it by the both ways. I tried to build it on my local machine. All attempts failed with the same result.
## Logs bellow
```sh
onetimesecret  | 172.21.160.1 - - [20/Apr/2025:07:31:29 +0000] "GET / HTTP/1.1" 200 8504 0.0059
onetimesecret  | 172.21.160.1 - - [20/Apr/2025:07:31:29 +0000] "GET /dist/assets/main.BZ7nPLfN.js HTTP/1.1" 404 8504 0.0052
onetimesecret  | 172.21.160.1 - - [20/Apr/2025:07:31:29 +0000] "GET /dist/assets/style.DJvioqMY.css HTTP/1.1" 404 8504 0.0071
onetimesecret  | 172.21.160.1 - - [20/Apr/2025:07:31:29 +0000] "GET /dist/assets/ZillaSlab-Bold.BSphAb8W.woff HTTP/1.1" 404 8504 0.0060
onetimesecret  | 172.21.160.1 - - [20/Apr/2025:07:31:29 +0000] "GET /dist/assets/ZillaSlab-Bold.CZCnI8e7.woff2 HTTP/1.1" 404 8504 0.0046
onetimesecret  | 172.21.160.1 - - [20/Apr/2025:07:31:29 +0000] "GET /dist/assets/ZillaSlab-BoldItalic.BG1CNiCK.woff HTTP/1.1" 404 8504 0.0065
onetimesecret  | 172.21.160.1 - - [20/Apr/2025:07:31:29 +0000] "GET /dist/assets/ZillaSlab-BoldItalic.q1iItYoI.woff2 HTTP/1.1" 404 8504 0.0089
onetimesecret  | 172.21.160.1 - - [20/Apr/2025:07:31:29 +0000] "GET /dist/assets/ZillaSlab-Italic.B4KlKyMb.woff HTTP/1.1" 404 8504 0.0069
onetimesecret  | 172.21.160.1 - - [20/Apr/2025:07:31:29 +0000] "GET /dist/assets/ZillaSlab-Italic.DQuJfL-3.woff2 HTTP/1.1" 404 8504 0.0049
onetimesecret  | 172.21.160.1 - - [20/Apr/2025:07:31:29 +0000] "GET /dist/assets/ZillaSlab-Regular.2Acx4doP.woff HTTP/1.1" 404 8504 0.0065
onetimesecret  | 172.21.160.1 - - [20/Apr/2025:07:31:29 +0000] "GET /dist/assets/ZillaSlab-Regular.CpTS5Ubm.woff2 HTTP/1.1" 404 8504 0.0070
```
## Config for the docker compose 
```yml
services:
  redis:
    image: redis:bookworm
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  onetimesecret:
    image: onetimesecret/onetimesecret:latest
    container_name: onetimesecret
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - COLONEL=admin@example.com
      - HOST=localhost:3000
      - SSL=false
      - RACK_ENV=production
    depends_on:
      - redis
    restart: always
```

**Comment by alexstojda** [comment]
Also seeing this!

**Comment by delano** [comment]
Thanks for the details and also the confirmation. 

My guess is that it's related to the [configuration changes](https://github.com/onetimesecret/onetimesecret/releases/tag/v0.21.0) in v0.21. I'll have a look at this today.

**Comment by delano** [comment]
I wasn't able to reproduce this in the time I had. I'll continue on it tomorrow.

**Comment by mbunkus** [comment]
Same problem for me. I'm using the following `docker-compose.yml`:

```yml
services:
  app:
    image: "ghcr.io/onetimesecret/onetimesecret:latest"
    restart: "unless-stopped"
    environment:
      AUTH_ENABLED: "false"
      ONETIME_DEBUG: "true"
      SSL: "true"
      HOST: "secrets.<actual domain name replaced>"
      REDIS_URL: "redis://redis:6379/0"
    depends_on:
      - "redis"
    ports:
      - "9400:3000"

  redis:
    image: "valkey/valkey:8.0-alpine"
    restart: "unless-stopped"
    environment:
      VALKEY_EXTRA_FLAGS: '--save 60 1 --loglevel warning'
    volumes:
      - "/srv/one-time-secret/redis-data:/data"

volumes:
  redis-data:
```

Can also confirm that replacing the `latest` tag with `v0.20.5` fixes it immediately.
