### ISSUE TITLE
v0.21.1 throws "Global secret cannot be nil"

### ISSUE THREAD

**Issue by screendriver** [onetimesecret/onetimesecret#1278]
Since `v0.21.1` was [released](https://github.com/onetimesecret/onetimesecret/issues/1259#issuecomment-2825437317) I'm getting the error `Global secret cannot be nil` when trying to start the container. I'm using the [lite version](https://github.com/onetimesecret/onetimesecret/blob/develop/docs/DOCKER-lite.md) of onetimesecret with a very minimal compose file:

```yaml
---
services:
  onetimesecret:
    image: ghcr.io/onetimesecret/onetimesecret-lite:v0.20.5
    environment:
      - HOST=my.domain.com
```
