### ISSUE TITLE
Setting COLONEL in env does not elevate user admin

### ISSUE THREAD

**Issue by jhob101** [onetimesecret/onetimesecret#1392]
If I understand correctly, setting the COLONEL environment variable to my email address should elevate me to admin when I register.

I have onetimesecret set up in a docker compose and environment variables in a  .env file with

```
COLONEL=myemail@example.com
```

However when I register with the same email as set in COLONEL I don't get admin priviledges, at least the UI looks exactly the same and if I try the /colonel route it redirects to the dashboard.

I've double-checked in portainer to ensure it has been correctly set, and that the email I register with is the same, but the result is the same.

Am I missing something or is this a bug?

**Comment by nvroot** [comment]
@delano can you provide working docker-compose example after each update something brokes a whole app

```
x-default-healthcheck: &default-healthcheck
  interval: 60s
  timeout: 20s
  retries: 5
  start_period: 60s
  start_interval: 5s
services:
  onetimesecret:
    image: 'onetimesecret/onetimesecret:latest'
    restart: unless-stopped
    container_name: onetimesecret
    environment:
      - AUTH_ENABLED=true
      - AUTH_SIGNUP=false
      - AUTH_SIGNIN=true
      - AUTH_AUTOVERIFY=true
      - COLONEL=admin@example.com
      - HOST=notes.example.com
      - RACK_ENV=production
      - REDIS_URL=redis://:changeme@onetimesecret-redis:6379/0
      - SECRET=secret
      - SSL=true
      - BUNDLE_INSTALL=true
    networks:
      - onetimesecret-network
      - proxy
    volumes:
      - "onetimesecret-data:/app"
    depends_on:
      - onetimesecret-redis
    healthcheck:
      test:
        - CMD
        - ruby
        - '-rnet/http'
        - '-e'
        - "exit(Net::HTTP.get_response(URI('http://localhost:3000')).is_a?(Net::HTTPSuccess) ? 0 : 1)"
      <<: *default-healthcheck
  onetimesecret-redis:
    image: redis:7-alpine
    command: redis-server --requirepass changeme
    restart: unless-stopped
    volumes:
      - "onetimesecret-redis:/data"
    networks:
      - onetimesecret-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      <<: *default-healthcheck
networks:
  onetimesecret-network:
    name: onetimesecret-network
    driver: bridge
  proxy:
    external: true
volumes:
  onetimesecret-data:
  onetimesecret-redis:
```

Doesn't works after last update, same happens on previous update too `- BUNDLE_INSTALL=true` doesn't resolve anymore

**Comment by jhob101** [comment]
Still not working for me I'm afraid after pulling the latest image from docker hub.

```
onetimesecret  | I(1746781853): [valid_email?] Address is valid (true): {"date":"2025-05-09 09:10:53 +0000","email":"me@example.com","validation_type":"regex","success":true,"errors":null,"smtp_debug":null,"configuration":{"validation_type_by_domain":null,"whitelist_validation":false,"whitelisted_emails":null,"blacklisted_emails":null,"whitelisted_domains":null,"blacklisted_domains":null,"blacklisted_mx_ip_addresses":null,"dns":["1.1.1.1","8.8.4.4","208.102.232.214"],"not_rfc_mx_lookup_flow":false,"smtp_fail_fast":false,"smtp_safe_check":true,"email_pattern":"default gem value","smtp_error_body_pattern":"default gem value"}}
onetimesecret  | I(1746781853): [new-customer] me@example.com customer 211.37.143.45 basic 5abqcqzfv760
```

Should I expect the output to say something like `new-colonel`?

This is my compose:

```
services:
  redis:
    image: redis:bookworm
    container_name: redis
    ports:
      - "6300:6379"
    networks:
      - secrets-net
  onetimesecret:
    image: onetimesecret/onetimesecret:latest
    container_name: onetimesecret
    depends_on:
      - redis
    env_file: ".env"
    ports:
      - "3030:3000"
    networks:
      - secrets-net
    restart: always
networks:
  secrets-net:
    driver: bridge
```
