### ISSUE TITLE
Refactor configuration into separate Static and Dynamic Configs

### ISSUE THREAD

**Issue by delano** [onetimesecret/onetimesecret#1452]
### Description
We want to split our monolithic configuration file (`config.example.yaml`) into two separate files: ~`config.static.yaml` for settings requiring application restart, and `config.dynamic.yaml` for runtime-adjustable settings~. We'll continue to use etc/config.yaml for what we're now calling static configuration; we'll use the new V2::SystemSettings model to store the dynamic config in redis. This has already been partially implemented, but we need to formalize the split and ensure consistent naming conventions between files.

[Configuration vs Settings Documentation](https://github.com/onetimesecret/onetimesecret/blob/7de016146a158691c854b6e626d599b06fd62ef7/docs/architecture/config-vs-settings.md)

### Key Changes
- Static config (`config.yaml`): Settings that require application restart
- Dynamic config (`config.dynamic.yaml`): Settings that can be changed at runtime
- Reorganized key naming for better clarity and organization

### TODO
- [x] Review the current split implementation to ensure completeness
- [x] Normalize naming conventions across both files
- [x] Update documentation to reflect the new configuration approach
- [x] Rename `:redis` to `:db` to prep for valkey

### Technical Considerations
- The existing code bases key names from the original single file structure
- Key name changes (like `:secret_options` → `business.secrets`) will require code updates
- Need to ensure backward compatibility for existing deployments
- Consider adding a validation layer for each config file at startup

<details>
<summary>Key Structure Changes</summary>

**Original (`config.example.yaml`) to New Structure**:

```
# Configuration mapping for splitting monolithic config into static and dynamic parts
# Static: Lives in etc/config.yaml
# Dynamic: Lives in the database via V2::SystemSettings model.

mappings:
  static:
    # Core site configuration
    - from: "site.host"
      to: "site.host"
    - from: "site.ssl"
      to: "site.ssl"
    - from: "site.secret"
      to: "site.secret"

    # Authentication core settings
    - from: "site.authentication.enabled"
      to: "site.authentication.enabled"
    - from: "site.authentication.colonels"
      to: "site.authentication.colonels"

    # Security settings
    - from: "site.authenticity"
      to: "site.authenticity"

    # Redis configuration
    - from: "redis"
      to: "db"

    # Email configuration
    - from: "emailer"
      to: "mail.connection"

    # Logging configuration
    - from: "logging"
      to: "logging"

    # Development settings
    - from: "development"
      to: "development"

    # Experimental features (runtime toggleable)
    - from: "experimental.allow_nil_global_secret"
      to: "experimental.allow_nil_global_secret"
    - from: "experimental.rotated_secrets"
      to: "experimental.rotated_secrets"
    - from: "experimental.freeze_app"
      to: "experimental.freeze_app"
    - from: "experimental.middleware."
      to: "site.middleware"

  dynamic:
    # UI interface settings
    - from: "site.interface.ui"
      to: "user_interface"

    - from: "site.authentication.signup"
      to: "user_interface.signup"
    - from: "site.authentication.signin"
      to: "user_interface.signin"
    - from: "site.authentication.verify"
      to: "user_interface.autoverify"

    # API interface settings
    - from: "site.interface.api"
      to: "api"

    # Secret options
    - from: "site.secret_options"
      to: "secret_options"

    # Feature flags
    - from: "features"
      to: "features"

    # Region
    - from: "site.regions"
      to: "features.regions"

    # Plans
    - from: "site.plans"
      to: "features.plans"

    # Domains
    - from: "site.domains"
      to: "features.domains"

    # Diagnostics
    - from: "diagnostics"
      to: "diagnostics"

    # Limits
    - from: "limits"
      to: "limits"

    # i18n
    - from: "internationalization"
      to: "features.internationalization"

    # Mail validation
    - from: "mail.truemail"
      to: "mail.validation.recipients"
    - from: "mail.truemail"
      to: "mail.validation.accounts"
```
</details>
