### ISSUE TITLE
Move plans definitions to static config YAML

### ISSUE THREAD

**Issue by delano** [onetimesecret/onetimesecret#1508]
Plans have been loaded start time since the dawn of time. 

```ruby
      def load_plans!
        add_plan :anonymous, 0, 0, ttl: 7.days, size: 100_000, api: false, name: 'Anonymous'
        add_plan :basic, 0, 0, ttl: 14.days, size: 1_000_000, api: true, name: 'Basic Plan', email: true,
          custom_domains: false, dark_mode: true
        add_plan :identity, 35, 0, ttl: 30.days, size: 10_000_000, api: true, name: 'Identity', email: true,
          custom_domains: true, dark_mode: true
        plans.freeze
      end
```

## Proposed Change

PRs: #1509 #1511 

We don't want to directly copy the plan details to the YAML equivalent although that was the original plan (see toggle below). That solves the hardcoded "pseudo-model" aspect, but doesn't solve the underlying problems:

1) The plan details combined system capabilities with functional boundaries. **Solution: split between the static config (capabilities) and mutable config (secret options).** 
2) Collided with the existing `plans` object in the core config. **Solution: Keep the structure but rename to `billing`**
3) The codebase uses the customer.planid field for UI logic. This is very limiting and makes the both the functionality and our ability to be flexible with plan types (e.g. A/B testing) very brittle. **Solution: simplify the options to just anonymous and authenticated.** Later we can use team level or object level permissions to re-introduce actual nuanced behaviours. 

### Static config

```yaml
capabilities:
  anonymous:
    api: true
    email: false
    custom_domains: false
  authenticated:
    api: true
    email: true
    custom_domains: false

# The pre-existing `plans` object has been renamed to `billing`
billing:
  enabled: <%= ENV['PLANS_ENABLED'] == 'true' || false %>
  stripe_key: <%= ENV['STRIPE_KEY'] || nil %>
  webhook_signing_secret: 'CHANGEME'
  payment_links:
    identity:
      tierid: identity
      month:
      year:
    dedicated:
      tierid: dedicated
      month:
      year:
```

### Mutable config

> [!WARNING]
> The move to mutable, db-backed configuration means that these env vars have become obsolete. For existing installs, running the config migration creates a etc/mutable.yaml file. When that file is loaded into the database, it will use the env vars at that point to set the values for anonymous users. After that, all other changes need to happen via the DB.

```yaml
secret_options:
  anonymous:
    # Default Time-To-Live (TTL) for secrets in seconds
    # This value is used if no specific TTL is provided when creating a secret
    default_ttl: <%= ENV['DEFAULT_TTL'] || nil %>
    # Available TTL options for secret creation (in seconds)
    # These options will be presented to users when they create a new secret
    # Format: String of integers representing seconds
    ttl_options: <%= (ENV['TTL_OPTIONS'] || nil) %>
  standard:
    default_ttl: null
    ttl_options: null
    size: null
  enhanced:
    default_ttl: null
    ttl_options: null
    size: null
```

<details><summary>Original structure</summary>
<p>

Let's move them to the static config YAML.

```yaml
plans:
  anonymous:
    ttl: 604800 # 7.days
    size: 100_000
    api: true
    name: 'Anonymous'
  basic:
    ttl: 1209600 # 14.days
    size: 1_000_000
    api: true
    name: 'Default Plan'
    email: true
    custom_domains: true
```

</p>
</details> 

### Opportunities

Improve terminology. Use terminology that describes what the system can do rather than how it's monetized.
