### ISSUE TITLE
Docker install bad css

### ISSUE THREAD

**Issue by CorneelSoete** [onetimesecret/onetimesecret#512]
After installing via docker-compose this is the page that loads at localhost:3000
![Screenshot from 2024-07-29 11-24-42](https://github.com/user-attachments/assets/0e8e99bf-23ca-420d-ae54-76647eac4ad1)

I have the following docker-compose.yml

```
#Onetimesecret
  onetimesecret:
    image: ghcr.io/onetimesecret/onetimesecret:latest
    container_name: onetimesecret
    hostname: onetimesecret
    ports:
      - "3000:3000"
    entrypoint: ["./bin/entrypoint.sh"]
    stdin_open: true
    tty: true
    environment:
      - HOST="localhost:3000"
      - SSL="true"
      - SECRET="CHANGEME"
      - REDIS_URL="redis://CHANGEME@redis:6379/0"
      - COLONEL="corneel.soete@gmail.com"
      - REDIS_PASSWORD="CHANGEME"
#    volumes:
#      - /home/Corneel/Documents/Projects/onetimesecret/Docker/onetimesecret:/app
    depends_on:
      - redis
    networks:
      glpi_network:
        ipv4_address: 172.20.0.4

#Redis
  redis:
    image: redis:bookworm
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - /home/Corneel/Documents/Projects/onetimesecret/Docker/redis/data:/data
      - /home/Corneel/Documents/Projects/onetimesecret/Docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      glpi_network:
        ipv4_address: 172.20.0.5


# network
networks:
  glpi_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1
```
