### ISSUE TITLE
 Unexpected error bad URI(is not URI?)

### ISSUE THREAD

**Issue by YouveGotMeowxy** [onetimesecret/onetimesecret#946]
I can't seem to get OTS to connect to my redis server and not sure why?

I have the OTS and Redis containers in the same docker network, and I have also setup a few other containers that use redis, of which I only ever need to enter "redis" as the redis URL, and it's PW. (No user, port, etc.)

Here is my Compose:

```
  onetimesecret:
    hostname: 'onetimesecret'
    image: 'onetimesecret/onetimesecret:latest'
    environment:
      TZ: 'America/Chicago'
      REDIS_URL: "redis://:<pw redacted>@redis"
      HOST: 'onetimesecret.mydomain.com'
      SSL: 'false'
      COLONEL: myemail+onetimesecret@gmail.com'
      RACK_ENV: 'production'
    #ports:
    #  - published: 3000
    #    target: 3000
    #    protocol: 'tcp'
    #    mode: 'host'
    deploy:
      mode: 'replicated'
      replicas: 1
      placement:
        constraints:
          - 'node.labels.Cloud == true'
      resources:
        limits:
          memory: '220M'
      restart_policy:
        condition: 'any'
    networks:
      - 'redis'
      - 'swag'
```

    Unexpected error `bad URI(is not URI?): "redis://:<pw redacted>@redis"` (URI::InvalidURIError)

Any ideas? TIA!
